# Minimale pacman-Konfiguration fuer Deutschland Anschnur BS DIN-Fertigungen.

[options]
Architecture = auto
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
