# Deutschland Anschnur BS Paketverwalterordnung.

[options]
Architecture = auto
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 5

[deutschland-anschnur]
SigLevel = Optional TrustAll
Server = https://chriopter.github.io/deutschland-anschnur-bs/$arch

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
